### ISSUE TITLE
Problem. It is not working with Node 0.4.12

### ISSUE THREAD

**Issue by murvinlai** [nateps/connect-gzip#10]
connect-gzip is not working with npm install in Node.0.4.12

It said "UNMET DEPENDENCY"

said it is not compatible with my version of node/npm   but I'm using the Node.0.4.12  npm 1.0.93

I don't want to run this on Unstable Node 0.5 version. anyway I can make it run on 0.4.12?

**Comment by mbrevoort** [comment]
since the dependency for connect is specified as "connect": ">= 1.4.0", it will pull that latest version of connect, which at this point is labelled "alpha" and has an engine dependency of >= 0.5 and < 0.7

**Comment by murvinlai** [comment]
so, what can I do?

**Comment by mbrevoort** [comment]
I decided to temporarily fork and fix the package.json dependency of connect. Then in my projects package.json I referenced the dependency like:

```
"connect-gzip": "git://github.com/mbrevoort/connect-gzip.git#v0.1.3-forked",
```

**Comment by nateps** [comment]
Thanks for reporting the issue.

Just fixed the package.json to require an appropriate version of connect. Try npm installing again.

**Comment by mbrevoort** [comment]
Awesome, thanks!
