### ISSUE TITLE
wrong logic for causing it not to gzip

### ISSUE THREAD

**Issue by shekhei** [nateps/connect-gzip#3]
In lib/gzip.js, line 67,68

``` javascript
if ( code !== 200 || !~accept.indexOf('gzip') || !matchType.test(type) || encoding)
```

should perhaps have been 

``` javascript
if ( code !== 200 || ~accept.indexOf('gzip') || !matchType.test(type) || encoding)
```

since !~accept.indexOf means found?

**Comment by nateps** [comment]
`~accept.indexOf('gzip')` will return a truthy value only if the Accept-Encoding header contains `'gzip'`. The code block following the conditional should execute only if the request shouldn't be gzipped, so the logic is correct. There are tests of this behavior in test/gzip.test.js.

**Comment by shekhei** [comment]
On the contrary, 

``` javascript
if(~"gzip".indexOf('gzip')){console.log("true");} // this outputs true
```

``` javascript
if(!~"gzip".indexOf('gzip')){console.log("true");} // this doesnt get executed(in which is the desired behavior isnt it?
```

**Comment by nateps** [comment]
As your example shows,

`if(!~"gzip".indexOf('gzip')){console.log("true");}`

does not log true. Each of these conditions are testing for things that should cause the content not to be gzipped. Therefore, the current logic is correct.

There are tests for Accept-Encoding headers that do and don't contain 'gzip', and it is working correctly. If this condition were backwards, this module would not work at all.

**Comment by shekhei** [comment]
Precisely, if the logic in the code is right, the first example should not be output.

And if the 2nd part doesnt get executed, that is the correct logic, which is not the case in the code right now. In the code, currently it is the first example, so actually, the correct logic should be the 2nd example not being executed, but in the code, the first example is actually being used.

---edit---

ah seems like i've made a mistake, sorry for that
