### ISSUE TITLE
gzip.staticGzip doesn't clean up old .gz files

### ISSUE THREAD

**Issue by respectTheCode** [nateps/connect-gzip#4]
Let it run for a while and you end up with tons of .gz files for every file that is being gzipped.

**Comment by Philipp15b** [comment]
Would it be possible to store the .gz files in a sort of temp directory?

**Comment by respectTheCode** [comment]
I am looking into doing this. The trick is getting it to clean up the old files. Every time a file is changed a new gz file is generated and the old one if left behind.

**Comment by nateps** [comment]
Old gz files should be deleted when new ones are generated thanks to contribution from @respectTheCode
