### ISSUE TITLE
staticGzip exposes internal fs path when a directory is accessed

### ISSUE THREAD

**Issue by sreuter** [nateps/connect-gzip#5]
My config:

app.use(gzip.staticGzip(__dirname + '/static',{maxAge: 8640000000}));

When a directory instead of an actual file is requested (without trailing slash), the staticGzip provider exposes the internal path of this directory (e.g. /home/node/myfaultyproject/static/js) to the client via a 301 Response 

connect.static doesn't do that... :-)

**Comment by nateps** [comment]
Yeah, that was pretty bad. Should be fixed now.
